### ISSUE TITLE
Card.card_set attribute usage

### ISSUE THREAD

**Issue by stroup-tmu** [andredavii/ezmem#1]
Hi Andre,

Since card_set is singular (not an array), you can just set the card_set for a card as follows:

card.card_set = CardSet.find(rand(1..8))
card.save

https://github.com/andredavii/ezmem/blob/359c61d6734df870d57d9f5ef7410aa3af057a6f/db/seeds.rb#L23

**Comment by andredavii** [comment]
Fixed Seed file with suggested fixes.
