### ISSUE TITLE
Comparison broken

### ISSUE THREAD

**Issue by stroup-tmu** [andredavii/ezmem#2]
It looks like the comparison is broken at the moment. You need to make sure you downcase the copied text, too, before comparing them.

https://github.com/andredavii/ezmem/blob/359c61d6734df870d57d9f5ef7410aa3af057a6f/app/controllers/learn_cards_controller.rb#L13

**Comment by andredavii** [comment]
added a new variable to compare with: @copied = params[:copied].downcase
